#!/usr/bin/env bash

cd "$(dirname $0)/.."

# assume that if there are no args, you want to switch to the configuration
cmd=${1:-switch}
shift

# without --fast nixos-rebuild will compile nix and use the compiled nix to
# evaluate the config, wasting several seconds
sudo nixos-rebuild "$cmd" --fast --file src/nixos.nix --log-format bar-with-logs "$@"
