#!/usr/bin/env bash

cd "$(dirname $0)/.."

# assume that if there are no args, you want to switch to the configuration
cmd=${1:-switch}
shift

# without --no-reexec nixos-rebuild will compile nix and use the compiled nix to
# evaluate the config, wasting several seconds
sudo nixos-rebuild "$cmd" --no-reexec --file src/nixos.nix --log-format bar-with-logs "$@"
